# NumPy – Numerical Python
## 1. Why Learn NumPy?

#### What is it?

NumPy is a powerful Python library for numerical computations. It provides fast and memory-efficient multi-dimensional arrays.

#### Why we need it?

1.Pure Python lists are slow for large datasets.

2.NumPy arrays are optimized for speed and vectorized operations.

3.Most Data Science & Machine Learning libraries (like Pandas, Scikit-Learn, TensorFlow) are built on top of NumPy.

#### Where is it used?

1.Data Analysis

2.Machine Learning & Deep Learning

3.Image Processing (OpenCV, PIL use NumPy arrays)

5.Scientific Computing & Simulations


In [1]:
## 2. Importing NumPy
import numpy as np

## 3. Arrays vs Python Lists
import numpy as np
import time

# Python list
py_list = [i for i in range(1000000)]

# NumPy array
np_array = np.arange(1000000)

# Time comparison
start = time.time()
sum(py_list)
print("Python list sum time:", time.time() - start)

start = time.time()
np.sum(np_array)
print("NumPy array sum time:", time.time() - start)



Python list sum time: 0.009020090103149414
NumPy array sum time: 0.0007004737854003906


## 4. Creating Arrays
1.np.arange(start, stop, step)

Purpose: Creates an array of numbers starting from start up to but not including stop, incremented by step.

Your code: np.arange(0, 10, 2)

Start = 0

Stop = 10 (exclusive)

Step = 2

2.np.linspace(start, stop, num)

Purpose: Creates an array of num equally spaced numbers between start and stop (inclusive).

Your code: np.linspace(0, 1, 5)

Start = 0

Stop = 1 (inclusive)

5 numbers evenly spaced

In [3]:
# From list 
arr = np.array([1, 2, 3, 4, 5])
print("Array:", arr)

# Zeros and Ones
print("Zeros:", np.zeros((2,3)))
print("Ones:", np.ones((2,3)))

# Range and Linspace
print("Arange:", np.arange(0, 10, 2))
print("Linspace:", np.linspace(0, 1, 5))

Array: [1 2 3 4 5]
Zeros: [[0. 0. 0.]
 [0. 0. 0.]]
Ones: [[1. 1. 1.]
 [1. 1. 1.]]
Arange: [0 2 4 6 8]
Linspace: [0.   0.25 0.5  0.75 1.  ]


In [9]:
## 5. Array Properties

arr = np.array([[1,2,3],[4,5,6]])
print("Array shape:", arr.shape)
print("Array dtype:", arr.dtype)
print("Array size:", arr.size)
print("Array ndim:", arr.ndim)

Array shape: (2, 3)
Array dtype: int64
Array size: 6
Array ndim: 2


In [10]:
## 6. Indexing and Slicing
arr = np.array([10,20,30,40,50])
print("Element at index 2:", arr[2])
print("Elements from index 1 to 3:", arr[1:4])
print("Elements at indices 0, 2, 4:", arr[[0,2,4]])
print("Every second element:", arr[::2])
print("Reversed array:", arr[::-1])


Element at index 2: 30
Elements from index 1 to 3: [20 30 40]
Elements at indices 0, 2, 4: [10 30 50]
Every second element: [10 30 50]
Reversed array: [50 40 30 20 10]


In [ ]:
matrix = np.array([[1,2,3],[4,5,6],[7,8,9]])
print("Matrix:\n", matrix)
print("Matrix shape:", matrix.shape)
print("Matrix dtype:", matrix.dtype)
print("Matrix size:", matrix.size)
print("Matrix ndim:", matrix.ndim)
print(matrix[0,1]) # element at row 0, col 1
print(matrix[1,:]) # entire row 1
print(matrix[:,2]) # entire col 2
# Matrix operations
print("Transpose:\n", matrix.T)
print("Sum of all elements:", np.sum(matrix))
print("Sum of each column:", np.sum(matrix, axis=0))
print("Sum of each row:", np.sum(matrix, axis=1))
print("Mean of all elements:", np.mean(matrix))
print("Mean of each column:", np.mean(matrix, axis=0))
print("Mean of each row:", np.mean(matrix, axis=1))
print("Element-wise multiplication:\n", matrix * 2)
print("Matrix multiplication:\n", np.dot(matrix, matrix))  

In [12]:
## 7. Operations and Broadcasting
a = np.array([1,2,3]) 
b = np.array([4,5,6])
print("a + b:", a + b)            # Element-wise addition
print("a * b:", a * b)            # Element-wise multiplication
print("a + 10:", a + 10)          # Broadcasting
print("a * 2:", a * 2)            # Broadcasting

a + b: [5 7 9]
a * b: [ 4 10 18]
a + 10: [11 12 13]
a * 2: [2 4 6]


In [15]:

## 8. Mathematical Functions
arr = np.array([1,2,3,4,5])
print("Sum:", np.sum(arr))
print("Mean:", np.mean(arr))
print("Max:", np.max(arr))
print("Min:", np.min(arr))
print("Standard Deviation:", np.std(arr))
print("Variance:", np.var(arr))
print("Square Root:", np.sqrt(arr))
print("Exponential:", np.exp(arr))
print("Logarithm:", np.log(arr))



Sum: 15
Mean: 3.0
Max: 5
Min: 1
Standard Deviation: 1.4142135623730951
Variance: 2.0
Square Root: [1.         1.41421356 1.73205081 2.         2.23606798]
Exponential: [  2.71828183   7.3890561   20.08553692  54.59815003 148.4131591 ]
Logarithm: [0.         0.69314718 1.09861229 1.38629436 1.60943791]


In [14]:
## 9. Reshaping Arrays
arr = np.arange(1, 13)
reshaped = arr.reshape((3,4))
print("Original array:", arr)
print("Reshaped array (3x4):\n", reshaped)
flattened = reshaped.flatten()
print("Flattened array:", flattened)

Original array: [ 1  2  3  4  5  6  7  8  9 10 11 12]
Reshaped array (3x4):
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
Flattened array: [ 1  2  3  4  5  6  7  8  9 10 11 12]


In [30]:
mat=np.array(range(1,10),ndmin=2)
mat1=mat.reshape(3,3)
print(mat1)
print(mat1[1:2])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[4 5 6]]


In [31]:
# 3.Find the mean, median, and standard deviation of [12, 15, 20, 25, 30].

arr=np.array([12,15,20,25,30])
print("Mean : ",np.mean(arr))
print("Median : ",np.median(arr))
print("Standard deviation : ",np.std(arr))

Mean :  20.4
Median :  20.0
Standard deviation :  6.529931086925803


In [3]:
# 4.Generate a random 5×5 matrix and find its maximum and minimum values.
 
# (Hint: Use np.random.rand for random numbers)

arr1=np.random.randint(0,100,(5,5))
print(arr1)
print("Max : ",np.max(arr1))
print("Min : ",np.min(arr1))

arr2=np.random.rand(25)
a=arr2.reshape(5,5)
print(a)
print("Max : ",np.max(arr2))
print("Min : ",np.min(arr2))

[[50 91 35 55  3]
 [26 57  8 58  8]
 [82 28 80 59 73]
 [99  3 34 84  2]
 [75 38 52 65 18]]
Max :  99
Min :  2
[[0.61866373 0.08723097 0.79325613 0.91744107 0.91969934]
 [0.32966416 0.23136069 0.48855674 0.70732475 0.00295874]
 [0.04938922 0.68971563 0.57344991 0.88904823 0.10812955]
 [0.76253017 0.05876991 0.5758781  0.86932737 0.41157828]
 [0.0867216  0.341939   0.8854875  0.37620831 0.50282416]]
Max :  0.9196993391676569
Min :  0.0029587411498742666
